name: game_tracker
description: A simple offline-first Flutter app to track completed games.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.5
  path_provider: ^2.1.4
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
